### ISSUE TITLE
parseRepeats и аналогичные методы заменить на инстанс Read

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/slack-telegram-bot#13]
Лучше все переводы из строки в значение делать явно через Read, причем в идеале у тебя должен соблюдаться закон что `show . read` не изменяет структуру и значение :)

**Comment by mrRomanovsky** [comment]
У меня есть предложение сделать это проще, не вводя новые типы данных и не меняя апи текущих тайпклассов: https://github.com/mrRomanovsky/slack-telegram-bot/commit/5bdc49bfe959f037649c21b3d891e9336b88e8d2

**Comment by Znack** [comment]
Окей, но в принципе можно было через newtype объявить обертку, для которой Read бы как раз символизировал, что именно эти сообщения именно таким образом энкодятся. Хотя текущее решение тоже в принципе норм, еще к тому же и компактнее :)
