### ISSUE TITLE
Убрать ошибки компиляции из-за TypeFamilyDependencies

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/slack-telegram-bot#19]
У тебя точно собирается проект? Я сразу же при сборке получил ошибку некорреткного парсинга :)

Вот так, мне кажется, должно быть 
![image](https://user-images.githubusercontent.com/2928964/44410537-d7d80e00-a58e-11e8-83b5-c5630a6a7078.png)

**Comment by mrRomanovsky** [comment]
Оказывается, это было результатом применения hindent. Я его прогонял последним, после всех исправлений в коде, не думая о том, что он может ввести некомплируемый код. https://github.com/mrRomanovsky/slack-telegram-bot/commit/b23147fd5ab36871e25d495fd2236d305f7898a7

**Comment by Znack** [comment]
Кстати да, с фундепами hindnent очень странно работает. Он вообще кстати в мультипараметрический тайпкласс может пустые фундепы попробовать засунуть, мы иногда из-за этого тупо `| a -> a` добавляли, чтобы он отстал :)
