### ISSUE TITLE
Не работает ТГ бот

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/slack-telegram-bot#22]
Попробовал затестить, но не работает отправка сообщений, хотя вроде я логи понатыкал в разных местах и везде все норм. 
Предлагаю тебе самому нормально в коде везде логи Debug уровня раскидать, я у себя обновленную версию потом запущу и тебе репорт скину, чтобы ты мог разобраться?

**Comment by mrRomanovsky** [comment]
Ошибся в сообщении closes и по началу закрыл этим коммитом другой ишью. https://github.com/mrRomanovsky/slack-telegram-bot/commit/b9ee820d512bbe44a0d5cb60804754c6a36fc0f0

**Comment by Znack** [comment]
Не-не, ты зря закрыл тут ишью, логи — только первый шаг, теперь мне надо запустить локально новую версию, воспроизвести ошибку и тебе отправить полученные логи :)
